FROM ghcr.io/developmentseed/titiler:latest

# CORS settings
ENV TITILER_API_CORS_ORIGINS=*
ENV TITILER_API_CORS_ALLOW_METHODS=GET,POST,OPTIONS

# Proxy settings for HTTPS detection
# ENV FORWARDED_ALLOW_IPS=*
# ENV TITILER_API_ROOT_PATH=""

ENV CPL_TMPDIR=/tmp
ENV GDAL_CACHEMAX=75%
ENV GDAL_INGESTED_BYTES_AT_OPEN=32768
ENV GDAL_DISABLE_READDIR_ON_OPEN=EMPTY_DIR
ENV GDAL_HTTP_MERGE_CONSECUTIVE_RANGES=YES
ENV GDAL_HTTP_MULTIPLEX=YES
ENV GDAL_HTTP_VERSION=2
ENV PYTHONWARNINGS=ignore
ENV VSI_CACHE=TRUE
ENV VSI_CACHE_SIZE=536870912

EXPOSE 7860

CMD ["uvicorn", "titiler.application.main:app", "--host", "0.0.0.0", "--port", "7860", "--workers", "1", "--proxy-headers", "--forwarded-allow-ips='*'", "--root-path=/api/v1/titiler"]